# Basic
title: KING
subtitle: To be a better man!
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 记录生活，记录技术，一个渴望成为大佬的菜鸟！
creator: <a href="http://onev.cat">@onevcat</a>

url: "https://blog.csdn.net/w_k_l"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: CSDN, description: My CSND, url: 'https://blog.csdn.net/w_k_l'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: KING
    # duoshuo: 
    
# Social
social:
    weibo: onevcat
    github: Kingwkl
    twitter: onevcat
    gplus: 107108267983477358170
    mail: kingkanglong@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
